---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-daemon
  namespace: kube-system
  labels:
    app.kubernetes.io/name: docker-daemon
    app.kubernetes.io/part-of: docker-daemon
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: docker-daemon
  template:
    metadata:
      labels:
        app.kubernetes.io/name: docker-daemon
        app.kubernetes.io/part-of: docker-daemon
    spec:
      containers:
        - name: dind
          image: docker:18.05-dind
          resources:
              limits:
                cpu: 2
                memory: 1Gi
              requests:
                cpu: 1
                memory: 1Gi
          securityContext:
              privileged: true
          volumeMounts:
            - name: dind-storage
              mountPath: /var/lib/docker
      volumes:
        - name: dind-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: docker
  namespace: kube-system
  labels:
    app.kubernetes.io/name: docker-daemon-service
spec:
  ports:
    - name: daemon
      port: 2375
      targetPort: 2375
      protocol: TCP

  selector:
    app.kubernetes.io/name: docker-daemon


    #  - name: DOCKER_HOST
    #    value: tcp://docker.svc.kube-system.cluster.local:2375