#!/bin/bash
curl -X GET http://admin:$1@localhost:8080/jenkins/job/CI/config.xml | tee CI.xml
curl -X GET http://admin:$1@localhost:8080/jenkins/job/Tag/config.xml | tee Tag.xml
curl -X GET http://admin:$1@localhost:8080/jenkins/job/Test/config.xml | tee Test.xml