spinnaker:
  halyard:
    additionalServiceSettings:
      deck.yml:
        env:
            API_HOST: http://localhost:8001/api/v1/namespaces/spinnaker/services/http:spin-gate:8084/proxy/
        kubernetes:
          securityContext:
            runAsUser: 0
## Kubernetes Dashboard
kubernetes-dashboard:
  rbac:
    create: true
    clusterAdminRole: true

# jenkins:
#   master:
#     jenkinsUriPrefix: /api/v1/namespaces/{{ Value.Release }}/services/http:cdplatform-jenkins:8080/proxy
